tasks:
  - name: update-initrd
    containerless: true
    workdir: "@BUILD_ROOT@"
    args:
      - '@SOURCE_ROOT@/scripts/make-initrd.sh'
      - '@SYSROOT_DIR@'
      - '@BUILD_ROOT@/initrd.tar'

  - name: make-iso
    containerless: true
    workdir: "@BUILD_ROOT@"
    tasks_required:
      - task: update-initrd
        order_only: true
    args:
      - "@SOURCE_ROOT@/scripts/make-iso.sh"
      - "@BUILD_ROOT@"
      - "@OPTION:arch@"
      - "yak-@OPTION:arch@.iso"

  - name: qemu
    tasks_required:
      - task: make-iso
        order_only: true
    tools_required:
      - host-ovmf-bin
    args:
      - "@SOURCE_ROOT@/scripts/qemu.sh"
      - '-sk'
      - "@OPTION:arch@"
      - "@BUILD_ROOT@/tools/host-ovmf-bin/ovmf-code-@OPTION:arch@.fd"
      - "@BUILD_ROOT@/yak-@OPTION:arch@.iso"
    workdir: "@BUILD_ROOT@"
    containerless: true
  - name: qemu-gdb
    tasks_required:
      - task: make-iso
        order_only: true
    tools_required:
      - host-ovmf-bin
    args:
      - "@SOURCE_ROOT@/scripts/qemu.sh"
      - '-skPD'
      - "@OPTION:arch@"
      - "@BUILD_ROOT@/tools/host-ovmf-bin/ovmf-code-@OPTION:arch@.fd"
      - "@BUILD_ROOT@/yak-@OPTION:arch@.iso"
    workdir: "@BUILD_ROOT@"
    containerless: true
  - name: yak-menuconfig
    workdir: "@BUILD_ROOT@"
    pkgs_required:
      - yak
    args:
      - "ninja"
      - "-C"
      - "@BUILD_ROOT@/pkg-builds/yak"
      - "menuconfig"
    environ:
      'LC_ALL': 'C.UTF-8'
      'TERM': 'xterm-256color'
